version: '3.7'

services:
  db:
    container_name: db
    image: postgres:15
    restart: unless-stopped
    environment:
        POSTGRES_DB: cashtrackDB
        POSTGRES_USER: cashtrackDBUser
        POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: node:22
    working_dir: /backend
    depends_on:
      - db
    ports:
      - 3000:3000
    command: sh -c "npm i && npm run start:dev"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/backend

  frontend:
    container_name: frontend
    image: node:22
    working_dir: /frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    command: sh -c "npm i && npm run dev"
    volumes:
      - ./frontend:/frontend

volumes:
  db-data:
    driver: local